spring:
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none



  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
management:
  endpoints:
    enabled-by-default=false: